@startuml
start
:Загрузить настройки;
:Проверить наличие источника и цели;
if (Доступны?) then (Да)
  :Начать копирование;
  if (Успешно?) then (Да)
    :Записать лог успеха;
  else (Нет)
    :Записать ошибку;
  endif
else (Нет)
  :Завершить с ошибкой;
endif
stop
@enduml
