@startuml
[*] --> Ожидание

Ожидание --> Выполняется : наступило время
Выполняется --> Успешно : завершено без ошибок
Выполняется --> Ошибка : ошибка копирования
Успешно --> [*]
Ошибка --> [*]
@enduml
